SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS new_table;
DROP TABLE IF EXISTS ASIGNATURAS;
DROP TABLE IF EXISTS PROFESORES;
DROP TABLE IF EXISTS Centros;




/* Create Tables */

CREATE TABLE ASIGNATURAS
(
	COD_ASIG char(8) NOT NULL,
	NOMBRE_ASI varchar(30),
	PRIMARY KEY (COD_ASIG),
	UNIQUE (COD_ASIG)
);


CREATE TABLE Centros
(
	COD_CENTRO decimal(4,0) NOT NULL,
	NOM_CENTRO varchar(20),
	DIRECTOR decimal(4,0),
	DIRECCION varchar(25),
	LOCALIDAD varchar(20),
	PROVINCIA varchar(20),
	PRIMARY KEY (COD_CENTRO),
	UNIQUE (COD_CENTRO)
);


CREATE TABLE new_table
(
	COD_ASIG char(8) NOT NULL,
	COD_PROF decimal(4,0) NOT NULL,
	UNIQUE (COD_ASIG),
	UNIQUE (COD_PROF)
);


CREATE TABLE PROFESORES
(
	COD_PROF decimal(4,0) NOT NULL,
	NOMBRE_APE varchar(30),
	NOMBRE_ESPE varchar(20),
	FECHA_NAC date,
	SEXO char(1),
	COD_CENTRO decimal(4,0) NOT NULL,
	PRIMARY KEY (COD_PROF),
	UNIQUE (COD_PROF),
	UNIQUE (COD_CENTRO)
);



/* Create Foreign Keys */

ALTER TABLE new_table
	ADD FOREIGN KEY (COD_ASIG)
	REFERENCES ASIGNATURAS (COD_ASIG)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROFESORES
	ADD FOREIGN KEY (COD_CENTRO)
	REFERENCES Centros (COD_CENTRO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE new_table
	ADD FOREIGN KEY (COD_PROF)
	REFERENCES PROFESORES (COD_PROF)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CENTROS
	ADD FOREIGN KEY (DIRECTOR)
	REFERENCES PROFESORES (COD_PROF)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
